name: sklearntoolsbasedev
dependencies:
    - python=3.6.2
    - nose
    - numpy
    - sympy
    - scikit-learn
    - six
    - pandas
    - pip:
        - toolz
        - git+ssh://git@github.com/jcrudy/sklearn2code.git